# escape=`
FROM plugins/base:windows-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Slack Blame" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release\drone-slack-blame.exe c:\drone-slack-blame.exe
ENTRYPOINT [ "c:\\drone-slack-blame.exe" ]
